/**
 * ## Quick revision
 *
 * - Entity — independent concept; relation — entities ka connection.
 * - Primary key — stable unique identity; foreign key — referenced identity.
 * - Normalization — repeated facts separate karo, update anomalies kam karo.
 * - Denormalization — read speed ke liye duplication; sync cost accept karo.
 * - One-to-many — child foreign key; many-to-many — join table.
 * - Constraint — business invariant ko DB par enforce karo.
 * - Money/time — precise numeric aur clear timezone/instant contract choose karo.
 * - Migration — schema changes versioned aur rollout-compatible rakho.
 * - Natural/surrogate key — business identity / generated ID; both ki uniqueness aur change policy clear.
 * - Delete model — hard delete ya soft delete; unique constraints, filtering aur retention accordingly.
 * - Data grain — ek row exactly kya represent karti hai, schema se pehle define.
 */

'use strict';


// -- Add a new column
// ALTER TABLE users ADD COLUMN phone VARCHAR(20);

// -- Drop a column
// ALTER TABLE users DROP COLUMN phone;

// -- Rename a column
// ALTER TABLE users RENAME COLUMN bio TO biography;

// -- Change column data type
// ALTER TABLE users ALTER COLUMN username TYPE TEXT;

// -- Set default value
// ALTER TABLE users ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

// -- Drop default value
// ALTER TABLE users ALTER COLUMN created_at DROP DEFAULT;

// -- Set NOT NULL
// ALTER TABLE users ALTER COLUMN email SET NOT NULL;

// -- Drop NOT NULL
// ALTER TABLE users ALTER COLUMN email DROP NOT NULL;

// -- Rename table
// ALTER TABLE users RENAME TO app_users;


// -- SERIAL (old way)
// CREATE TABLE products (
//     id SERIAL PRIMARY KEY,
//     name VARCHAR(100)
// );

// -- IDENTITY (modern way)
// CREATE TABLE products (
//     id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
//     name VARCHAR(100)
// );

// -- GENERATED BY DEFAULT AS IDENTITY (allows manual override)
// CREATE TABLE products (
//     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     name VARCHAR(100)
// );


// CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
//
// CREATE TABLE diary (
//     id SERIAL PRIMARY KEY,
//     entry TEXT,
//     current_mood mood
// );
//
// INSERT INTO diary (entry, current_mood) VALUES ('Great day!', 'happy');
// INSERT INTO diary (entry, current_mood) VALUES ('Not so great', 'blah');  -- ❌ ERROR!

// -- Add new enum value
// ALTER TYPE mood ADD VALUE 'excited' AFTER 'happy';


// -- Approach 1: Separate nullable FK columns
// CREATE TABLE likes (
//     id SERIAL PRIMARY KEY,
//     user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
//     post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
//     comment_id INTEGER REFERENCES comments(id) ON DELETE CASCADE,
//     CHECK (
//         COALESCE((post_id)::BOOLEAN::INTEGER, 0) +
//         COALESCE((comment_id)::BOOLEAN::INTEGER, 0) = 1
//     )
//     -- Exactly ONE of post_id or comment_id must be set
// );

// -- Approach 3: Separate tables (cleanest, but more tables)
// CREATE TABLE post_likes (
//     id SERIAL PRIMARY KEY,
//     user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
//     post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
//     UNIQUE(user_id, post_id)
// );
//
// CREATE TABLE comment_likes (
//     id SERIAL PRIMARY KEY,
//     user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
//     comment_id INTEGER REFERENCES comments(id) ON DELETE CASCADE,
//     UNIQUE(user_id, comment_id)
// );


// CREATE TABLE rectangles (
//     id SERIAL PRIMARY KEY,
//     width NUMERIC NOT NULL,
//     height NUMERIC NOT NULL,
//     area NUMERIC GENERATED ALWAYS AS (width * height) STORED
// );

// INSERT INTO rectangles (width, height) VALUES (5, 10);
// SELECT * FROM rectangles;  -- area = 50 (automatically computed)


// CREATE TEMP TABLE active_users AS
// SELECT * FROM users WHERE last_login > '2024-01-01';
//
// SELECT * FROM active_users;  -- works in same session
// -- Session end → table gone


const designRules = {
    normalize: '3NF for most apps',
    primaryKey: 'Every table MUST have a PK',
    foreignKey: 'FK constraints enforce integrity',
    identity: 'Use IDENTITY over SERIAL',
    naming: 'snake_case, plural table names',
    timestamps: 'Always add created_at, updated_at'
};

console.log('Schema design rules:', designRules);
